### ISSUE TITLE
FSM immutability

### ISSUE THREAD

**Issue by veyndan** [anupcowkur/statelin#3]
A `machine` should be immutable once instantiated, as otherwise the state of the machine can never be guaranteed due to the possibility of additional states being added to the FSM during simulation.

The current implementation therefore contradicts the `README`:

> State machines allow us to explicitly model the possible states and transitions of our applications. This allows us to define what's possible in the system upfront and prevent bugs like "When X happens and Y happens and Z happens, some random thing happens".

**Comment by anupcowkur** [comment]
Good point. This might require a public API change though. One possibility is to have a `machine.start()` method. You can add states and handlers before calling this method. Once this method is called, any modifications will throw an exception.

Any better ideas?

@ErikHellman would appreciate your thoughts on this as well.

**Comment by veyndan** [comment]
I feel the most natural implementation would be using a DSL and just returning an immutable machine. Therefore we don't have to intricately handle mutability inside of the project.

**Comment by anupcowkur** [comment]
see #9
