### ISSUE TITLE
Cannot read State name (Cannot Serialize state)

### ISSUE THREAD

**Issue by corlaez** [anupcowkur/statelin#8]
The current implementation won't allow me to read the name of the sate I am using. I consider this a terrible decition since now I cannot serialize state to persist it in a file for example.

Can we allow State to read the name value that holds?

Right now I have to use reflection to get it. :(

**Comment by corlaez** [comment]
I noticed that Trigger does not have this problem since is a data class and only has a String as value. However State is not a data class and it does not consider different classes with the same name the same. (there is also the onEntry an exit and I don't have a clear answer on how to handle that)

**Comment by anupcowkur** [comment]
see #9
